const rows = [
  [
    'phoenix-plumage',
    'Plumas da fênix',
    '#ff8738',
    'Elementos',
    'Plumas de fogo se abrem em leque, com nervuras incandescentes e pontas que se desfazem.',
  ],
  [
    'argent-crossroads',
    'Encruzilhada de prata',
    '#b9d9ee',
    'Magia',
    'Quatro correntes de prata se entrelaçam, com nós luminosos que percorrem suas curvas.',
  ],
  [
    'coral-bloom',
    'Coral arcano',
    '#ff839f',
    'Natureza',
    'Ramos de coral luminoso crescem em três conjuntos e liberam pequenos brotos.',
  ],
  [
    'mercury-ribbon',
    'Faixas de mercúrio',
    '#88d5e7',
    'Magia',
    'Faixas líquidas se dobram, refletindo luz em faces largas e bordas finas.',
  ],
  [
    'ink-bloom',
    'Tinta do abismo',
    '#9c72e8',
    'Magia',
    'Manchas escuras se abrem em veios ramificados, com bordas violetas e espaços vazios.',
  ],
  [
    'lotus-wake',
    'Lótus das marés',
    '#48d8eb',
    'Elementos',
    'Pétalas de água se desdobram; películas transparentes deixam espuma nas cristas.',
  ],
  [
    'thorn-covenant',
    'Pacto de espinhos',
    '#8ed476',
    'Natureza',
    'Ramos arqueados entrelaçam espinhos e pequenas folhas com nervuras claras.',
  ],
  [
    'starlit-fall',
    'Queda de estrelas',
    '#8fbcff',
    'Magia',
    'Cometas pequenos cruzam em direções diferentes, com núcleos quentes e caudas afiladas.',
  ],
  [
    'moon-shards',
    'Estilhaços lunares',
    '#bad9ff',
    'Magia',
    'Fragmentos lunares facetados orbitam e giram, com brilhos percorrendo as faces.',
  ],
  [
    'golden-moths',
    'Mariposas solares',
    '#ffd976',
    'Natureza',
    'Mariposas de luz abrem asas delicadas em ritmos distintos, deixando pó dourado.',
  ],
  [
    'crimson-lattice',
    'Trama carmesim',
    '#ef5d86',
    'Magia',
    'Veios vivos se cruzam e pulsam; bifurcações deixam fios luminosos no chão.',
  ],
  [
    'frost-lotus',
    'Lótus de geada',
    '#86e5ff',
    'Elementos',
    'Cristais radiais crescem em nervuras ramificadas, com faces frias e pó de gelo.',
  ],
  [
    'ether-sail',
    'Velas do éter',
    '#b7a1ff',
    'Magia',
    'Três membranas leves se dobram como seda, com bordas iluminadas e interior translúcido.',
  ],
  [
    'obsidian-sun',
    'Sol de obsidiana',
    '#ffb45d',
    'Magia',
    'Fragmentos escuros atravessam uma coroa de calor, deixando frestas de luz e brasas.',
  ],
  [
    'thunder-roots',
    'Raízes do trovão',
    '#99bcff',
    'Elementos',
    'Descargas bifurcadas percorrem o chão em pulsos alternados, com clarão e decaimento.',
  ],
  [
    'jade-cocoons',
    'Casulos de jade',
    '#53e3b1',
    'Natureza',
    'Casulos translúcidos flutuam em alturas distintas; nervuras internas ondulam e refletem.',
  ],
  [
    'sand-chronicle',
    'Memórias de areia',
    '#e5bd82',
    'Elementos',
    'Dunas pequenas se dissolvem em correntes de areia, com cristas claras e partículas finas.',
  ],
  [
    'opal-cascade',
    'Cascata de opalas',
    '#81e1ef',
    'Magia',
    'Gotas de opala se alongam e se encontram, com núcleos refratados e películas de luz.',
  ],
  [
    'soul-tethers',
    'Fios da alma',
    '#a383ff',
    'Magia',
    'Três fios sinuosos ligam pequenas almas luminosas que se afastam e retornam.',
  ],
  [
    'nova-breath',
    'Respiração de nova',
    '#ffbd87',
    'Elementos',
    'Uma pressão luminosa avança em frentes irregulares e se desfaz em filamentos de plasma.',
  ],
] as const;
export const livingEffectKinds = rows.map((row) => row[0]);
export type LivingEffectKind = (typeof rows)[number][0];
export const livingEffects = rows.map(([kind, name, color, group, description]) => ({
  kind,
  name,
  color,
  group,
  description,
}));
