// Additional IDs are appended so saved rooms retain the original ordering.
export const extraEffectKinds = [
  'inferno',
  'blue-fire',
  'acid-rain',
  'hail',
  'ice-lattice',
  'steam',
  'sandstorm',
  'earthquake',
  'thunderstorm',
  'bubbles',
  'solar-halo',
  'lunar-halo',
  'starfield',
  'comets',
  'mirror-shield',
  'prismatic-barrier',
  'clockwork',
  'gravity-well',
  'astral-threads',
  'spectral-chains',
  'thorn-cage',
  'spores',
  'mushrooms',
  'butterflies',
  'feathers',
  'rage',
  'sleep',
  'fear',
  'petrify',
  'soul-flames',
] as const;
export const extraEffects = [
  {
    kind: 'inferno',
    name: 'Círculo infernal',
    color: '#ff693c',
    group: 'Elementos',
    description: 'Labaredas altas em uma coroa irregular, chão incandescente e brasas com rastros.',
  },
  {
    kind: 'blue-fire',
    name: 'Fogo azul',
    color: '#79ccff',
    group: 'Elementos',
    description: 'Chamas estreitas com núcleo branco e línguas azuis torcidas em torno da base.',
  },
  {
    kind: 'acid-rain',
    name: 'Chuva ácida',
    color: '#b3da67',
    group: 'Elementos',
    description:
      'Gotas corrosivas caem sobre o chão e abrem pequenos respingos e vapor esverdeado.',
  },
  {
    kind: 'hail',
    name: 'Granizo',
    color: '#b5e9ff',
    group: 'Elementos',
    description: 'Pedras de gelo facetadas caem, quicam e se fragmentam em pequenos estilhaços.',
  },
  {
    kind: 'ice-lattice',
    name: 'Mandala de gelo',
    color: '#c3eaff',
    group: 'Elementos',
    description: 'Cristal de seis pontas cresce sob os pés, com ramificações e facetas luminosas.',
  },
  {
    kind: 'steam',
    name: 'Vapor quente',
    color: '#e5cabc',
    group: 'Elementos',
    description: 'Jatos de vapor se abrem em plumas curvas, com condensação nas bordas.',
  },
  {
    kind: 'sandstorm',
    name: 'Tempestade de areia',
    color: '#d6ac6b',
    group: 'Elementos',
    description: 'Faixas densas de areia giram com grãos rápidos, poeira e trilhas curvas.',
  },
  {
    kind: 'earthquake',
    name: 'Fissuras sísmicas',
    color: '#c69568',
    group: 'Elementos',
    description: 'Rachaduras ramificadas se abrem no chão, com lascas de pedra e tremores locais.',
  },
  {
    kind: 'thunderstorm',
    name: 'Tempestade elétrica',
    color: '#a7beff',
    group: 'Elementos',
    description: 'Nuvens ao redor da base descarregam relâmpagos ramificados e gotas de chuva.',
  },
  {
    kind: 'bubbles',
    name: 'Bolhas mágicas',
    color: '#7ed7ed',
    group: 'Elementos',
    description:
      'Bolhas translúcidas sobem com reflexos curvos, brilho delicado e pequenas ondulações.',
  },
  {
    kind: 'solar-halo',
    name: 'Coroa solar',
    color: '#ffd37b',
    group: 'Magia',
    description: 'Raios em pétalas cercam a base, com uma coroa dourada pulsante e centelhas.',
  },
  {
    kind: 'lunar-halo',
    name: 'Véu lunar',
    color: '#bdd1ff',
    group: 'Magia',
    description: 'Crescente prateado orbita a base com poeira lunar e arcos suaves de luz.',
  },
  {
    kind: 'starfield',
    name: 'Constelações',
    color: '#b9abff',
    group: 'Magia',
    description: 'Estrelas conectadas desenham constelações móveis com pulsos percorrendo os fios.',
  },
  {
    kind: 'comets',
    name: 'Cometas orbitais',
    color: '#ffaaca',
    group: 'Magia',
    description: 'Cometas percorrem órbitas curvas, deixando caudas afiladas e núcleos brilhantes.',
  },
  {
    kind: 'mirror-shield',
    name: 'Escudos espelhados',
    color: '#c7e6ef',
    group: 'Magia',
    description: 'Placas refletoras facetadas orbitam com bordas de metal e reflexos móveis.',
  },
  {
    kind: 'prismatic-barrier',
    name: 'Barreira prismática',
    color: '#b7acff',
    group: 'Magia',
    description: 'Facetas translúcidas em várias cores formam uma proteção com refração e brilhos.',
  },
  {
    kind: 'clockwork',
    name: 'Engrenagens arcanas',
    color: '#d8b37d',
    group: 'Magia',
    description: 'Engrenagens dentadas giram em sentidos opostos sobre um mostrador luminoso.',
  },
  {
    kind: 'gravity-well',
    name: 'Poço gravitacional',
    color: '#a493eb',
    group: 'Magia',
    description: 'Disco escuro deforma arcos de luz enquanto partículas convergem em órbitas.',
  },
  {
    kind: 'astral-threads',
    name: 'Fios astrais',
    color: '#8fe1dc',
    group: 'Magia',
    description: 'Fios luminosos se entrelaçam ao redor da base, com nós e pulsos viajantes.',
  },
  {
    kind: 'spectral-chains',
    name: 'Correntes espectrais',
    color: '#aebfff',
    group: 'Magia',
    description:
      'Elos de corrente translúcidos circundam o corpo, com reflexos e energia espectral.',
  },
  {
    kind: 'thorn-cage',
    name: 'Coroa de espinhos',
    color: '#86b66b',
    group: 'Natureza',
    description: 'Galhos espinhosos crescem sob o corpo, com folhas pequenas e pontas afiadas.',
  },
  {
    kind: 'spores',
    name: 'Esporos luminosos',
    color: '#b7d782',
    group: 'Natureza',
    description: 'Nuvem delicada de esporos brilha em alturas distintas sobre uma névoa suave.',
  },
  {
    kind: 'mushrooms',
    name: 'Círculo de cogumelos',
    color: '#d29edb',
    group: 'Natureza',
    description: 'Cogumelos com chapéus e lamelas surgem na base, liberando pequenas partículas.',
  },
  {
    kind: 'butterflies',
    name: 'Borboletas encantadas',
    color: '#ecafce',
    group: 'Natureza',
    description: 'Borboletas com asas desenhadas e movimento de voo percorrem caminhos sinuosos.',
  },
  {
    kind: 'feathers',
    name: 'Penas ao vento',
    color: '#e5d6b3',
    group: 'Natureza',
    description: 'Penas com hastes e barbas se inclinam e giram em correntes suaves de ar.',
  },
  {
    kind: 'rage',
    name: 'Fúria',
    color: '#ee7654',
    group: 'Estado',
    description:
      'Marcas de corte, pulsos vermelhos e rastros angulares revelam a energia da fúria.',
  },
  {
    kind: 'sleep',
    name: 'Sono encantado',
    color: '#c0aff0',
    group: 'Estado',
    description: 'Pequenos crescentes e sinais de sono flutuam com estrelas e névoa calmante.',
  },
  {
    kind: 'fear',
    name: 'Medo',
    color: '#a995b7',
    group: 'Estado',
    description: 'Garras de sombra e olhos espectrais surgem entre véus escuros pulsantes.',
  },
  {
    kind: 'petrify',
    name: 'Petrificação',
    color: '#b7aaa0',
    group: 'Estado',
    description: 'Crosta de pedra acompanha a silhueta com fraturas, facetas e detritos caindo.',
  },
  {
    kind: 'soul-flames',
    name: 'Chamas de almas',
    color: '#84dcc9',
    group: 'Estado',
    description: 'Fios de fogo espectral e pequenas máscaras de luz giram ao redor da base.',
  },
] as const;
