// Appended IDs are stable for saved scenes; all twenty fields have distinct geometry.
export const arcanaEffectKinds = [
  'liquid-aegis',
  'aurora-veil',
  'light-cathedral',
  'mirror-helix',
  'plasma-flower',
  'nebula-mantle',
  'living-eclipse',
  'tidal-lens',
  'storm-lances',
  'floating-prisms',
  'arcane-harmony',
  'ruby-heart',
  'constellation-breath',
  'aether-drops',
  'celestial-rosette',
  'gravity-fold',
  'discharge-matrix',
  'threshold-wings',
  'abyssal-veil',
  'sapphire-iris',
] as const;
export type ArcanaEffectKind = (typeof arcanaEffectKinds)[number];
const rows: [ArcanaEffectKind, string, string, string][] = [
  [
    'liquid-aegis',
    'Escudo líquido',
    '#1dbbff',
    'Uma membrana azul translúcida ondula, com brilho nas bordas e correntes dentro da esfera.',
  ],
  [
    'aurora-veil',
    'Véu de aurora',
    '#39efb6',
    'Véus luminosos se dobram e deslizam em ritmos diferentes ao redor do personagem.',
  ],
  [
    'light-cathedral',
    'Arcos da catedral',
    '#ffbd45',
    'Três arcos de luz se abrem e se desfazem em poeira dourada.',
  ],
  [
    'mirror-helix',
    'Hélice de espelhos',
    '#64dfff',
    'Duas correntes espelhadas se entrelaçam e mudam de profundidade.',
  ],
  [
    'plasma-flower',
    'Flor de plasma',
    '#ff508e',
    'Lóbulos de plasma se estendem, se encontram e recuam como uma flor viva.',
  ],
  [
    'nebula-mantle',
    'Manto de nebulosa',
    '#9859ff',
    'Nuvens de luz violeta giram lentamente, com recortes vazios e poeira estelar.',
  ],
  [
    'living-eclipse',
    'Eclipse vivo',
    '#ffa73a',
    'Uma sombra curva atravessa a coroa luminosa, abrindo um crescente irregular.',
  ],
  [
    'tidal-lens',
    'Lente de marés',
    '#1ad7eb',
    'Ondas de refração atravessam uma lente de água, com espuma fina e centro transparente.',
  ],
  [
    'storm-lances',
    'Lanças da tempestade',
    '#378dff',
    'Três descargas curvas avançam e se apagam alternadamente, deixando rastros elétricos.',
  ],
  [
    'floating-prisms',
    'Prismas flutuantes',
    '#ab70ff',
    'Prismas facetados orbitam em alturas diferentes, com reflexos que percorrem suas faces.',
  ],
  [
    'arcane-harmony',
    'Harmonia arcana',
    '#ff73d6',
    'Três frentes de energia interferem em curvas suaves e deixam nós de luz.',
  ],
  [
    'ruby-heart',
    'Núcleo de rubi',
    '#ff345d',
    'Três cristais de rubi pulsam em alturas distintas, com reflexos nas faces e poeira luminosa.',
  ],
  [
    'constellation-breath',
    'Sopro de constelações',
    '#4dbaff',
    'Estrelas seguem trilhas divergentes e liberam poeira celeste em ciclos suaves.',
  ],
  [
    'aether-drops',
    'Gotas do éter',
    '#28ecd2',
    'Gotas transparentes se deformam e percorrem órbitas independentes, com reflexos nas bordas.',
  ],
  [
    'celestial-rosette',
    'Rosácea celeste',
    '#ffcb59',
    'Uma rosácea de luz dobra suas pétalas, alternando o tamanho e a profundidade dos lóbulos.',
  ],
  [
    'gravity-fold',
    'Dobra gravitacional',
    '#845dff',
    'Dois arcos alongados dobram o espaço em direções opostas e deixam uma faixa luminosa.',
  ],
  [
    'discharge-matrix',
    'Matriz de descargas',
    '#54d5ff',
    'Pontos de energia se ligam por descargas intermitentes, com ramificações que mudam de trajeto.',
  ],
  [
    'threshold-wings',
    'Asas do limiar',
    '#41e3ff',
    'Duas asas de energia se abrem e se recolhem com filamentos que fluem nas extremidades.',
  ],
  [
    'abyssal-veil',
    'Véu abissal',
    '#b64aff',
    'Véus sombrios se afastam do centro, atravessados por rasgos violetas e névoa translúcida.',
  ],
  [
    'sapphire-iris',
    'Íris de safira',
    '#249fff',
    'Lâminas luminosas de uma íris se dobram e se abrem ao redor do personagem.',
  ],
];
export const arcanaEffects = rows.map(([kind, name, color, description]) => ({
  kind,
  name,
  color,
  description,
  group: 'Magia',
}));
