import type { EffectKind } from './vtt-effects';
const cues: Record<EffectKind, string> = {
  death: 'necrotic',
  fire: 'fire',
  frost: 'ice',
  poison: 'poison',
  heal: 'healing',
  sparks: 'electric',
  lightning: 'thunder',
  arcane: 'arcane',
  shield: 'shield',
  radiant: 'healing',
  shadow: 'necrotic',
  acid: 'poison',
  wind: 'wind',
  water: 'water',
  earth: 'earth',
  vines: 'leaves',
  portal: 'portal',
  teleport: 'portal',
  shockwave: 'sonic',
  explosion: 'explosion',
  vortex: 'wind',
  smoke: 'wind',
  blizzard: 'ice',
  embers: 'fire',
  'chain-lightning': 'thunder',
  lava: 'fire',
  runes: 'arcane',
  curse: 'necrotic',
  bless: 'healing',
  necrotic: 'necrotic',
  web: 'leaves',
  swarm: 'swarm',
  leaves: 'leaves',
  petals: 'leaves',
  blades: 'blades',
  sonic: 'sonic',
};
export function effectSound(kind: EffectKind) {
  return '/audio/vtt-effects/' + cues[kind] + '.wav';
}
