import { z } from 'zod';
export const dayModes = ['original', 'dawn', 'afternoon', 'dusk', 'night'] as const;
export const weatherModes = [
  'clear',
  'partly-cloudy',
  'cloudy',
  'overcast',
  'drizzle',
  'rain',
  'thunderstorm',
  'snow',
  'blizzard',
  'hail',
  'fog',
  'mist',
  'wind',
  'tornado',
  'hurricane',
  'ash',
  'sandstorm',
  'luminous-sky',
  'blood-rain',
  'mana-storm',
  'arcane-fog',
  'void-storm',
  'eclipse',
  'meteors',
  'frozen-hell',
  'sunshower',
  'spectral-storm',
  'ethereal-drizzle',
  'wild-winds',
] as const;
export const atmosphereSchema = z
  .object({
    enabled: z.boolean().default(false),
    day: z.enum(dayModes).default('original'),
    weather: z.enum(weatherModes).default('clear'),
    intensity: z.number().min(0).max(1).default(0.65),
    wind: z.number().min(0).max(360).default(115),
    speed: z.number().min(0.1).max(2).default(0.65),
  })
  .strict();
export type MapAtmosphere = z.infer<typeof atmosphereSchema>;
export const dayPresets = [
  { id: 'original', name: 'Luz original', hint: 'Conservar as cores do mapa' },
  { id: 'dawn', name: 'Amanhecer', hint: 'Luz rosada e horizonte dourado' },
  { id: 'afternoon', name: 'Sol da tarde', hint: 'Luz quente e feixes suaves' },
  { id: 'dusk', name: 'Entardecer', hint: 'Âmbar, sombras violetas' },
  { id: 'night', name: 'Noite', hint: 'Azul profundo e luar' },
] as const;
export const weatherPresets = [
  ['clear', 'Céu limpo', 'natural', 'none'],
  ['partly-cloudy', 'Parcialmente nublado', 'natural', 'cloud'],
  ['cloudy', 'Nublado', 'natural', 'cloud'],
  ['overcast', 'Céu encoberto', 'natural', 'cloud'],
  ['drizzle', 'Garoa', 'natural', 'rain'],
  ['rain', 'Chuva', 'natural', 'rain'],
  ['thunderstorm', 'Tempestade', 'natural', 'storm'],
  ['snow', 'Neve', 'natural', 'snow'],
  ['blizzard', 'Nevasca', 'natural', 'snow'],
  ['hail', 'Granizo', 'natural', 'hail'],
  ['fog', 'Neblina', 'natural', 'fog'],
  ['mist', 'Névoa leve', 'natural', 'fog'],
  ['wind', 'Ventania', 'natural', 'wind'],
  ['tornado', 'Tornado', 'natural', 'vortex'],
  ['hurricane', 'Furacão', 'natural', 'vortex'],
  ['ash', 'Cinzas', 'natural', 'ash'],
  ['sandstorm', 'Tempestade de areia', 'natural', 'sand'],
  ['luminous-sky', 'Céu luminoso', 'magic', 'aurora'],
  ['blood-rain', 'Chuva de sangue', 'magic', 'rain'],
  ['mana-storm', 'Tempestade de mana', 'magic', 'storm'],
  ['arcane-fog', 'Neblina arcana', 'magic', 'fog'],
  ['void-storm', 'Tempestade do vazio', 'magic', 'storm'],
  ['eclipse', 'Eclipse celestial', 'magic', 'eclipse'],
  ['meteors', 'Chuva de meteoros', 'magic', 'meteor'],
  ['frozen-hell', 'Inferno gélido', 'magic', 'snow'],
  ['sunshower', 'Chuva de sol', 'magic', 'rain'],
  ['spectral-storm', 'Tempestade espectral', 'magic', 'storm'],
  ['ethereal-drizzle', 'Garoa etérea', 'magic', 'rain'],
  ['wild-winds', 'Ventos de magia selvagem', 'magic', 'wind'],
] as const;
export const weatherPreset = (id: MapAtmosphere['weather']) =>
  weatherPresets.find((p) => p[0] === id)!;
