// Context-specific terms for the licensed item translation. Longer phrases
// take precedence, so Light property and the Light spell remain distinct.
export const itemRulesGlossary: Record<string, string> = {
  'Light property': 'propriedade Leve',
  'Heavy property': 'propriedade Pesada',
  'Two-Handed property': 'propriedade Duas mãos',
  'Finesse property': 'propriedade Acuidade',
  'Versatile property': 'propriedade Versátil',
  'Attack action': 'ação Atacar',
  'Bonus Action': 'ação bônus',
  'Magic action': 'ação Magia',
  'Utilize action': 'ação Utilizar',
  'Dash action': 'ação Disparar',
  'Dodge action': 'ação Esquivar',
  'Help action': 'ação Ajudar',
  'saving throws': 'testes de resistência',
  'saving throw': 'teste de resistência',
  'Strength (Athletics) check': 'teste de Força (Atletismo)',
  'Dexterity (Sleight of Hand) check': 'teste de Destreza (Prestidigitação)',
  'Sleight of Hand': 'Prestidigitação',
  'ability checks': 'testes de atributo',
  'ability check': 'teste de atributo',
  'ability scores': 'valores de atributo',
  'ability score': 'valor de atributo',
  'ability modifier': 'modificador de atributo',
  'attack rolls': 'jogadas de ataque',
  'attack roll': 'jogada de ataque',
  'damage rolls': 'rolagens de dano',
  'damage roll': 'rolagem de dano',
  'Hit Point maximum': 'máximo de pontos de vida',
  'Hit Point': 'ponto de vida',
  'Hit Points': 'pontos de vida',
  'Temporary Hit Points': 'pontos de vida temporários',
  'Short Rest': 'descanso curto',
  'Long Rest': 'descanso longo',
  'spell slots': 'espaços de magia',
  'spell slot': 'espaço de magia',
  'spell attack modifier': 'modificador de ataque de magia',
  'spellcasting ability': 'atributo de conjuração',
  'spell save DC': 'CD de resistência de magia',
  'Armor Class': 'Classe de Armadura',
  'Bright Light': 'luz plena',
  'Dim Light': 'penumbra',
  Darkvision: 'visão no escuro',
  'Difficult Terrain': 'terreno difícil',
  Initiative: 'iniciativa',
  'Proficiency Bonus': 'bônus de proficiência',
  Concentration: 'concentração',
  Attunement: 'sintonia',
  Attuned: 'sintonizado',
  charges: 'cargas',
  charge: 'carga',
  Poisoned: 'Envenenado',
  Exhaustion: 'Exaustão',
  Restrained: 'Impedido',
  Blinded: 'Cego',
  Deafened: 'Surdo',
  Invisible: 'Invisível',
  Paralyzed: 'Paralisado',
  Petrified: 'Petrificado',
  Resistance: 'resistência',
  Immunity: 'imunidade',
  Vulnerability: 'vulnerabilidade',
  Advantage: 'vantagem',
  Disadvantage: 'desvantagem',
  Speed: 'deslocamento',
  turn: 'turno',
  round: 'rodada',
  DC: 'CD',
  AC: 'CA',
  Armor: 'armadura',
  'cubic foot': 'pé cúbico',
  'cubic feet': 'pés cúbicos',
  'square foot': 'pé quadrado',
  'square feet': 'pés quadrados',
  foot: 'pé',
  feet: 'pés',
  inches: 'polegadas',
  inch: 'polegada',
  miles: 'milhas',
  mile: 'milha',
  pounds: 'libras',
  pound: 'libra',
  ounces: 'onças',
  ounce: 'onça',
  gallons: 'galões',
  gallon: 'galão',
  pints: 'pintas',
  pint: 'pinta',
  quarts: 'quartos de galão',
  quart: 'quarto de galão',
  'fluid ounces': 'onças fluidas',
  'fluid ounce': 'onça fluida',
  liters: 'litros',
  liter: 'litro',
  Athletics: 'Atletismo',
  Acrobatics: 'Acrobacia',
  Perception: 'Percepção',
  Stealth: 'Furtividade',
  Arcana: 'Arcanismo',
  Investigation: 'Investigação',
  Persuasion: 'Persuasão',
  Deception: 'Enganação',
  Intimidation: 'Intimidação',
  'Animal Handling': 'Lidar com Animais',
  Survival: 'Sobrevivência',
  Medicine: 'Medicina',
  Insight: 'Intuição',
  spellcaster: 'conjurador',
  Bard: 'bardo',
  Cleric: 'clérigo',
  Druid: 'druida',
  Paladin: 'paladino',
  Ranger: 'patrulheiro',
  Sorcerer: 'feiticeiro',
  Warlock: 'bruxo',
  Wizard: 'mago',
};

export const spellNamesPortuguese: Record<string, string> = {
  'Animal Messenger': 'Mensageiro Animal',
  'Chain Lightning': 'Relâmpago em Cadeia',
  'Create or Destroy Water': 'Criar ou Destruir Água',
  'Death Ward': 'Proteção contra a Morte',
  'Detect Poison and Disease': 'Detectar Veneno e Doença',
  'Disguise Self': 'Disfarçar-se',
  'Faerie Fire': 'Fogo das Fadas',
  'Fire Storm': 'Tempestade de Fogo',
  'Flaming Sphere': 'Esfera Flamejante',
  'Giant Insect': 'Inseto Gigante',
  'Globe of Invulnerability': 'Globo de Invulnerabilidade',
  Grease: 'Área Escorregadia',
  'Guardian of Faith': 'Guardião da Fé',
  Heal: 'Cura Completa',
  'Ice Storm': 'Tempestade de Gelo',
  'Insect Plague': 'Praga de Insetos',
  "Leomund's Tiny Hut": 'Pequena Cabana de Leomund',
  'Locate Animals or Plants': 'Localizar Animais ou Plantas',
  'Mage Armor': 'Armadura Arcana',
  'Mage Hand': 'Mãos Mágicas',
  "Mordenkainen's Private Sanctum": 'Santuário Particular de Mordenkainen',
  "Otiluke's Resilient Sphere": 'Esfera Resiliente de Otiluke',
  'Phantasmal Force': 'Força Fantasmagórica',
  'Ray of Enfeeblement': 'Raio do Enfraquecimento',
  'Remove Curse': 'Remover Maldição',
  Scrying: 'Vidência',
  'Shining Smite': 'Golpe Brilhante',
  Slow: 'Lentidão',
  'Stone Shape': 'Moldar Rochas',
  Stoneskin: 'Pele de Pedra',
  Tsunami: 'Tsunami',
  'Wall of Thorns': 'Muralha de Espinhos',
  'Water Walk': 'Caminhar sobre as Águas',
  'Wind Wall': 'Muralha de Vento',
  Light: 'Luz',
  Daylight: 'Luz do Dia',
  Darkness: 'Escuridão',
  Alarm: 'Alarme',
  'Animate Objects': 'Animar Objetos',
  'Animate Dead': 'Animar Mortos',
  'Alter Self': 'Alterar-se',
  'Animal Friendship': 'Amizade Animal',
  Awaken: 'Despertar',
  'Arcane Lock': 'Tranca Arcana',
  Bane: 'Perdição',
  Banishment: 'Banimento',
  Barkskin: 'Pele de Árvore',
  'Blade Barrier': 'Barreira de Lâminas',
  Bless: 'Bênção',
  'Blindness/Deafness': 'Cegueira/Surdez',
  Blur: 'Turvar',
  'Burning Hands': 'Mãos Flamejantes',
  'Call Lightning': 'Convocar Relâmpagos',
  'Charm Person': 'Enfeitiçar Pessoa',
  Clairvoyance: 'Clarividência',
  Cloudkill: 'Névoa Mortal',
  Command: 'Comando',
  'Comprehend Languages': 'Compreender Idiomas',
  'Cone of Cold': 'Cone de Frio',
  Confusion: 'Confusão',
  'Conjure Elemental': 'Conjurar Elemental',
  'Control Weather': 'Controlar o Clima',
  'Cure Wounds': 'Curar Ferimentos',
  'Dancing Lights': 'Luzes Dançantes',
  Darkvision: 'Visão no Escuro',
  'Detect Evil and Good': 'Detectar o Bem e o Mal',
  'Detect Magic': 'Detectar Magia',
  'Detect Thoughts': 'Detectar Pensamentos',
  'Dimension Door': 'Porta Dimensional',
  Disintegrate: 'Desintegrar',
  'Dispel Magic': 'Dissipar Magia',
  'Dominate Beast': 'Dominar Fera',
  'Dominate Person': 'Dominar Pessoa',
  'Dominate Monster': 'Dominar Monstro',
  Earthquake: 'Terremoto',
  'Enhance Ability': 'Aprimorar Atributo',
  'Enlarge/Reduce': 'Aumentar/Reduzir',
  Entangle: 'Constrição',
  Etherealness: 'Forma Etérea',
  Fear: 'Medo',
  'Feather Fall': 'Queda Suave',
  'Find the Path': 'Encontrar o Caminho',
  Fireball: 'Bola de Fogo',
  'Fire Shield': 'Escudo de Fogo',
  'Flame Strike': 'Coluna de Chamas',
  Fly: 'Voo',
  'Fog Cloud': 'Névoa Obscurecente',
  'Freedom of Movement': 'Movimentação Livre',
  'Gaseous Form': 'Forma Gasosa',
  Gate: 'Portal',
  'Greater Restoration': 'Restauração Maior',
  'Gust of Wind': 'Rajada de Vento',
  Haste: 'Acelerar',
  'Hold Monster': 'Imobilizar Monstro',
  'Hold Person': 'Imobilizar Pessoa',
  'Hypnotic Pattern': 'Padrão Hipnótico',
  Identify: 'Identificar',
  Invisibility: 'Invisibilidade',
  Jump: 'Salto',
  Knock: 'Arrombar',
  Levitate: 'Levitação',
  'Lesser Restoration': 'Restauração Menor',
  'Lightning Bolt': 'Relâmpago',
  'Locate Creature': 'Localizar Criatura',
  'Locate Object': 'Localizar Objeto',
  'Magic Missile': 'Mísseis Mágicos',
  'Mass Cure Wounds': 'Curar Ferimentos em Massa',
  'Minor Illusion': 'Ilusão Menor',
  'Mirror Image': 'Imagem Espelhada',
  'Pass without Trace': 'Passos sem Pegadas',
  Passwall: 'Criar Passagem',
  'Plane Shift': 'Viagem Planar',
  Polymorph: 'Metamorfose',
  'Prismatic Spray': 'Rajada Prismática',
  'Protection from Evil and Good': 'Proteção contra o Bem e o Mal',
  'Raise Dead': 'Reviver os Mortos',
  Regenerate: 'Regeneração',
  Resurrection: 'Ressurreição',
  Revivify: 'Revivificar',
  'Scorching Ray': 'Raio Ardente',
  'See Invisibility': 'Ver o Invisível',
  Sending: 'Mensagem',
  Shatter: 'Despedaçar',
  Shield: 'Escudo Arcano',
  'Speak with Animals': 'Falar com Animais',
  'Speak with Dead': 'Falar com os Mortos',
  'Speak with Plants': 'Falar com Plantas',
  'Spike Growth': 'Crescer Espinhos',
  'Stinking Cloud': 'Névoa Fétida',
  Suggestion: 'Sugestão',
  Sunburst: 'Explosão Solar',
  Telekinesis: 'Telecinese',
  Teleport: 'Teletransporte',
  Tongues: 'Idiomas',
  'True Resurrection': 'Ressurreição Verdadeira',
  'Wall of Fire': 'Muralha de Fogo',
  'Wall of Force': 'Muralha de Energia',
  'Wall of Ice': 'Muralha de Gelo',
  'Wall of Stone': 'Muralha de Pedra',
  Web: 'Teia',
  'Wind Walk': 'Caminhar no Vento',
  Wish: 'Desejo',
  'Zone of Truth': 'Zona da Verdade',
};
