import type { Point } from '../shared/vtt';
export const pingDuration = 2700;
export type VttPing = Point & { at: number };
export function drawPing(c: CanvasRenderingContext2D, ping: VttPing, zoom: number) {
  const elapsed = Math.max(0, Date.now() - ping.at);
  if (elapsed >= pingDuration) return;
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const phase = (elapsed % 900) / 900;
  const bounce = reduced ? 0 : 22 * Math.pow(1 - phase, 3);
  c.save();
  c.translate(ping.x, ping.y);
  c.scale(1 / zoom, 1 / zoom);
  c.translate(0, -bounce);
  c.lineJoin = 'round';
  c.shadowColor = '#f1b659';
  c.shadowBlur = 14;
  const gradient = c.createLinearGradient(0, -58, 0, 0);
  gradient.addColorStop(0, '#8d5d27');
  gradient.addColorStop(0.55, '#f7d58d');
  gradient.addColorStop(1, '#ffefc8');
  c.fillStyle = gradient;
  c.strokeStyle = '#402a18';
  c.lineWidth = 2;
  c.beginPath();
  c.moveTo(-5, -55);
  c.lineTo(5, -55);
  c.lineTo(5, -22);
  c.lineTo(18, -22);
  c.lineTo(0, 0);
  c.lineTo(-18, -22);
  c.lineTo(-5, -22);
  c.closePath();
  c.fill();
  c.stroke();
  c.shadowBlur = 0;
  c.strokeStyle = '#fff6d9';
  c.lineWidth = 1;
  c.beginPath();
  c.moveTo(-3, -52);
  c.lineTo(-3, -20);
  c.lineTo(-13, -20);
  c.stroke();
  c.restore();
}
